[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "internai-embeddings"
version = "1.0.0"
description = "Embeddings client for InternAI platform"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24.0",
    "requests>=2.31.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.6.0",
]

openai = [
    "openai>=1.0.0",
]

mistral = [
    "mistralai>=0.0.11",
]

local = [
    "sentence-transformers>=2.2.0",
    "torch>=2.0.0",
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
target-version = "py311"
line-length = 88
select = [
    "E", "W", "F", "I", "B", "C4", "UP"
]
ignore = [
    "E501", "B008", "C901"
]
